name: pgadmin
version: 1.0.0
appVersion: 1.0
description: pgAdmin is a web based administration tool for the PostgreSQL database.
keywords:
  - pgadmin
  - postgres
  - database
  - sql
home: https://www.pgadmin.org/