name: Helm PR Workflow

on:
  pull_request:
  workflow_dispatch:

jobs:

  lint-test:
    runs-on: ubuntu-latest
    name: Helm Chart Lint
    env:
      CT_CHART_DIRS: charts
      CT_TARGET_BRANCH: $GITHUB_BASE_REF
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - uses: azure/setup-helm@v3
        with:
          version: 'v3.8.2' # default is latest (stable) test
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
        id: install

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch $GITHUB_BASE_REF)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch $GITHUB_BASE_REF

      - name: Create kind Kubernetes cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --target-branch $GITHUB_BASE_REF