## Reference: https://github.com/helm/chart-testing-action
---
name: Linting and Testing
on:
  push:

jobs: 
  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@v2.2.1

      - name: List changed charts
        id: list-changed
        run: |
          ## If executed with debug this won't work anymore.
          changed=$(ct --config ./.github/configs/ct-lint.yaml list-changed)
          charts=$(echo "$changed" | tr '\n' ' ' | xargs)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
            echo "::set-output name=changed_charts::$charts"
          fi
      
      # we will build and use this PR in the meantime
      # ref: https://github.com/helm/chart-testing/pull/445

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: install custom chart-testing (ct CLI)
        run: |
          git clone -b ft-add-registry-support https://github.com/jcsf/chart-testing.git
          cd chart-testing
          go build -o /usr/local/bin/ct ct/main.go
      
      - name: Run chart-testing (lint)
        run: |
          /usr/local/bin/ct lint --debug \
            --config ./.github/configs/ct-lint.yaml \
            --lint-conf ./.github/configs/lintconf.yaml \
            --helm-repo-extra-args finx="--username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}"
      
      - name: Install helm-docs
        id: helm-docs
        run: |
            cd /tmp
            wget https://github.com/norwoodj/helm-docs/releases/download/v1.11.0/helm-docs_1.11.0_Linux_armv6.tar.gz
            tar -xvf helm-docs_1.11.0_Linux_armv6.tar.gz
            sudo mv helm-docs /usr/local/sbin
      
      - name: Run Helm-Docs
        run: |
            cd usr/local/sbin
            chmod +x helm-docs
            helm-docs
            
      